### ISSUE TITLE
Split agents.rs to separate models and services to isolate domains

### ISSUE THREAD

**Issue by sanhomealex** [jetli/rust-yew-realworld-example-app#11]
agents.rs is a big file with a lots of code and domains implemented.
It is hard to support such a big code files.

This will be good to split this file to a separate models and services that will concentrate on particular domains, e.g. authentication, articles, comments and etc.

![new_structure](https://user-images.githubusercontent.com/48746578/79045752-5fb3d580-7c15-11ea-91af-76cb2ed71bdb.png)

I made my example of how this can be done and like to share it.
Please allow me to push to a separate "feature" branch, so then you can review and merge if this will be suitable.

**Comment by jetli** [comment]
@sanhomealex Thanks for feedback, I split files for types and services, and re-export to eliminate changes in other mods. If you want any further refactoring, you can just fork this repo to your account, make changes and send a pull request.

**Comment by sanhomealex** [comment]
Hi @jetli !
Thank you for the updates. 
That is exactly what I meant.
