### ISSUE TITLE
Is there a reason to not use trunk?

### ISSUE THREAD

**Issue by maxcountryman** [jetli/rust-yew-realworld-example-app#31]
This project mentions its goal is to produce a project sample that adheres closely to Yew idioms. As far as build tooling goes, I'm curious why [Trunk](https://trunkrs.dev) isn't used?

**Comment by jetli** [comment]
Just my laziness I think :), since building ain't broken yet, but I will look into trunk soon, thanks.

**Comment by cisen** [comment]
+1

**Comment by jetli** [comment]
upgrade to use trunk
