### ISSUE TITLE
How do you configure the router to work with whatever.github.io/repo path

### ISSUE THREAD

**Issue by s1n7ax** [jetli/rust-yew-realworld-example-app#35]
I'm trying to host my sample website on GitHub pages but I'm struggling to get router working.

This is the website
https://s1n7ax.github.io/my-website/

It's showing `404` page because there is no route `/my-website`. How did you manage get it working on your website? Plus, I noticed all the links has `rust-yew-realworld-example-app`. How are you doing all that?

![image](https://user-images.githubusercontent.com/18459807/169345832-e888b415-dbda-4326-b217-0466013001b3.png)

**Comment by jetli** [comment]
for yew 0.19, I have to use a commit like this: https://github.com/jetli/rust-yew-realworld-example-app/commit/4b4748c8b7a340e98c61a2b6c6d6a9eab5e3384f
```rust
#[at("/rust-yew-realworld-example-app/login")]
Login,
```
for master version of yew, you can use hash router or base name, like:
https://jetli.github.io/yew-hooks/#/use_toggle

**Comment by s1n7ax** [comment]
Apparently they can use `<base data-trunk-public-url />` in header with trunk. When compiling, --public-url should be passed.
