### ISSUE TITLE
I can't  find the logfile for this project

### ISSUE THREAD

**Issue by QuintinTao** [jetli/rust-yew-realworld-example-app#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

I ran this project in the ubuntu system.There are some "Http Request Error" on the Sign Up page. But I can't find the log files for this project.

**Additional context**

**Comment by QuintinTao** [comment]
I ran this project in the ubuntu system.There are some "Http Request Error" on the Sign Up page. But I can't find the log files for this project.

**Comment by QuintinTao** [comment]
![image](https://user-images.githubusercontent.com/72123724/170675798-f70b1520-c1c7-4de1-a053-f921f5e25b96.png)

**Comment by jetli** [comment]
did you do this step to setup env for backend api address: `cp .env.example .env`
and you can see log in your browser's console.
