### ISSUE TITLE
shows blank screen whether compiled in docker or even on localhost

### ISSUE THREAD

**Issue by kolinfluence** [jetli/rust-yew-realworld-example-app#48]
shows blank screen whether compiled in docker or even on localhost

**Comment by Andrew0314** [comment]
I have the same issue

**Comment by crispinb** [comment]
I really don't want to `+1` , but did either of you posting here find the cause of this?

**Comment by jetli** [comment]
@crispinb  did you install `cargo install wasm-bindgen-cli`? maybe wasm-bindgen-cli is not automatically installed by default.

**Comment by crispinb** [comment]
Thanks @jetli  - I already had that installed.
It appears to be parcel-related. From the console:

```js
Uncaught ReferenceError: __exports is not defined
    parcelRequire<["../node_modules/parcel-plugin-wasm.rs/wasm-loader.js"]< wasm-loader.js:2
```

I only had a brief attempt to run this while starting to explore Yew, and haven't dug any further than that yet.

**Comment by jetli** [comment]
switched to trunk
