### ISSUE TITLE
Anchor links on hover do not show the link it will navigate to

### ISSUE THREAD

**Issue by damodharanj** [jetli/rust-yew-realworld-example-app#6]
**Describe the bug**
Anchor on hover show the link to be navigated on bottom left corner in chrome. But its not showing in the app.

**Comment by jetli** [comment]
Yes, this is a bug in yew-router, I've already reported an issue for it: https://github.com/yewstack/yew_router/issues/225, I will wait for it to be fixed or might try to submit a PR to yew-router later, thanks.

**Comment by jetli** [comment]
Sent a PR to yew-router： https://github.com/yewstack/yew_router/pull/228, and waiting for review.

**Comment by jetli** [comment]
PR is merged, wait for a new release.

**Comment by jetli** [comment]
Upgraded to latest version.
