### ISSUE TITLE
Make the API root URL configurable

### ISSUE THREAD

**Issue by LukeMathWalker** [jetli/rust-yew-realworld-example-app#7]
Hey!

I was trying to run this frontend in combination with the Rust (Tide + Diesel) backend we wrote (https://github.com/colinbankier/realworld-tide) and I realised that it's currently impossible to configurable the URI of the backend, given that it's hard-coded as
```rust
const API_ROOT: &str = "https://conduit.productionready.io/api";
```

Would it be possible to make it configurable, either via a configuration file or an environment variable?
It would be amazing to be able to give instructions to run a full Rust web-app, FE+BE, without having to ask the user to touch the source code :grin:

**Comment by jetli** [comment]
Great idea! A .env config should fit for this. I'll investigate it later.

**Comment by jetli** [comment]
Continue to investigate why new value of API_ROOT is not picked up when editing .env file to trigger a new build.
